[build]
  command = "npm run jam-prod"
  publish = "dist/static"

[[headers]]
  # Set the default header to the one we want for documents
  for = "/*"
    [headers.values]
    
    Report-To = '''{
        "group":"default",
        "max_age":31536000,
        "endpoints":[{"url":"https://jeffschoonover.report-uri.com/a/d/g"}],
        "include_subdomains":true
    }'''
    NEL = '''{
        "report_to":"default",
        "max_age":31536000,
        "include_subdomains":true
    }'''
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
      default-src 'none';
      connect-src 'self';
      script-src none;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src https://fonts.gstatic.com;
      img-src 'self' https://res.cloudinary.com;
      base-uri 'self';
      form-action 'none';
      frame-ancestors 'none';
      sandbox allow-scripts allow-same-origin;
      report-uri https://jeffschoonover.report-uri.com/r/d/csp/enforce;
      report-to report-uri;'''
    
    
    
    
    
    

    
    
    
